# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Style/StringLiterals:
  EnforcedStyle: single_quotes

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "public/**/*"
    - "spec/cassettes/**/*"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - spec/**/*
    - db/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Max: 100
  Exclude:
    - "**/*_spec.rb"
    - "**/environments/*"

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
